language: java
before_install:
- pip install --user requests
install: true
script:
- mvn clean install
deploy:
  provider: script
  script: mvn deploy
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: "cfGitRUDYHL0bRV7xzCjx8eTSvJA2n1WP43RKk0yI0GYaYYk3x4GO1PYHC79gQzdECo9nQQrA41/3/BKd0airH1m/zmNqGIKWBTLKnNGwHhmh/V6rlNTSh2/Jru/svntk0ILKIV5hq3xqKz4RzlRNllTYGbRJWcTXJQe9K6cYPlSWBJDxNqIK8FKblYCEKGquuEaW7ZdvZ41zu77n3AGgomydURvCFzw4NaIwERreveL/ibEc7jEuMCogmvE4bDSEU6J0PaDAgXVZO+Xy/bycvVQ6Un9Lzt8do/AH20OxMizq+OZm7aBQKJyPnnOKXscQzW4zkrqHT1mGKILwBIQ409teUp3TlaYWDihask9P+eoLSUg+eO/2cHCLyz6my3net2MRr2YdMdOtbIwH9YxmOnjouYZepxrPE1pdwcMkMqlAWNSW8Um3IaDttwrhzzIXwA7CxL4Ji9U2fzK3/g1Os28rRxKbsPTlklJZvWgHYPcUzLnbBlPUzHulPE4XyePzkR6AHH5ImMEAawnPuyyenRFdXXds1aMuxWUrtZPw/AbkwrOnFkJ0JLah0imHSyzzE/EDV1ZOUhny5RestiE27d7jw9RCQKXPHYj/pXwEF1GvjjbotbsQA3ry32vnKUJfbtTkKZv4YSEE/aBsxTAe+TiiUcYw4i+lHKujUv46FE="
  - secure: "dl7m5dRMIpdDAKu/WLvAgkG97ksPndU2JiBX4sMMn/Oofv9N/Y96Ft4q9dYcdu4G3n0FCy0LsyFRkLIdRmGtwEDpbuXqOo+sfflz/wwOYwRssI6eKdXKqaoOWchjfS1ovScLUIWVkoyhdT0D2KULlj+6OjHpMEg+8mCTF89oBFtj1iCwAN5dd++6D8cZX5A7qT39PeE4rovFVclVcwJyOZvh/nEolb7Wfa5J0JBVnQR0JiSQx5wm6IUz8RCRAsmFYCV/TpTStkKOINs4l7GzUbxTxU5KOFSTP57W2ucIShGGZbfcpv/StgRBa2d4KJM4+8HUuG3sD2aWYoQn6fcvYA9nz2z3pfyAG4TKVJKWFc6wE/s+FtuzqtZAC8mzY6NF66Jw2Qp79+3S4wlqr3ksE6yvZg8NlAu5T7Sl9QwH0+MHKznfEmCR2OQ8poCpwRdqWXmddqVrJe32jNH5GbmYHSIGfLYczLdIZqs9yFubQlJ635+wcWaWfPU3xVUxWUuCMPBYscMyAzyxJ1CgNssRe80PQAL9p4TeTYn/nwQ2S/M0oKCrP+jXOZtMXS7mIUaofOzljmoTcwtmJ6BgJi1HLvBTG71JY2eAtFN5s1umU/8a/eD5CxMjSxYXSxFUp5Fb5L8vvNeBWDTwd1yk+VLcHmfPDcNz7YjUKdWIJUc1x5c="