language: java
install: true
script:
- mvn --settings settings.xml clean install
deploy:
  provider: script
  script: mvn --settings settings.xml deploy
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: "cRtQB8g9XxEgamT8Wu39cZvDnjOl120sJbapuxK8S4pcZlFnnkvCcgy6me0Ur7ATJV03pAH1EqvLGN+zRFscuLzJ42egAGPIsJdUhcISeTmK/5qdf4n7+rjr2iENrajCNgK6RrOjeQmhAlL/55YGLOXKnB2E00nMDNrg6OJaEC7m0xBs/rhs0a9SeDeN0Bz1/FIyx6R3LHEWrnV4zFo5ojaKIv7KMt4d01jySQoCz3PdSpc1v46uJ3rf2TXXahy++jtec1diIdHflcVcSF3j81yhereb59ObL/6iRWweCsvFOhkKonVg59HlR5dHDpF3ZlqIpS/a5MHzT+/Nx0GqLyNHRZn37NQpEvST6ZW3C2lPiVeWvJ6XXyXwaYq5m+mkgoaXzb96K3dIMJ2bYVx7N6P0I9NMxBpRg8mJCVpbh70G2YOgcmCNCxRL/bZN+2RsRVOw4OJNj3liC/VhdV/82azePBqGLP4n2SUt9XV0habQsaBLCpOMkF9SIt5NAS/PoAYpaKMM9C7XEaDJjlqmErflNIFiOidt8SAzdfpNIDnClB3AuKuKXY1CgY8hbYplOzlEh+HeoUIhb6j62AqUdwl82ilb5VWis93h8yCSCJi9NdfFDPRj6gy7JGUWDfk4MFUuGGXYm4ht23MITYcm5eC93SJJzDwZ1tiH+uS1bOM="