language: java
script:
- cd plantuml.eclipse.releng/
- mvn clean install
- cd ..
cache:
  bundler: true
  directories:
  - plantuml.eclipse.updatesite/target
  - "$HOME/.m2"
deploy:
  provider: releases
  api_key:
    secure: rjhdO9XkqYIu0TUkWjJVSNF9D82+y8j7EJ2knCX4ZHL4cuZeSJnxJEdpAxIFw+oGrUU/F66CuZJcI2Xj/9dEZWgZG7NJ6N40zODL3Rkt/TiIiyHCpbB+se23E7jKOviUvvsJopelJdFJf4h66RWWe3sS/dck9Dw3ZxTrcr8Udw0Pfhcxa5/y9MfvR+cNx536PSr2E9AzkpBQIABlcHUTI0xlWGXaVsFYfhqP5u5wgK0j+O3ifj/rnn0vyE/BofVOZli18C1r/qLi3gSnxp1eIDAAi5XZTCvusbATwHhwc99gGx3tKW0VoFHpiMHTT6neOfKSfntMyHOcxh496VQq+LjAGDDUhVA7fmfXp0NOVOeWPRSbGjY/1hTsp9T81VuYpqgzjDHjZK/i4072eNe813YYqVWR9yVzQGekS46Qb2S0LEKuqWKd436iXa1ysrJzEFF8f6nxhEN3zQiNX6uhx8BNY/pmBzZn/C1JRViYLNdB9KO6emoaGWfevMiOpwKi0+lEluDFIZu1JMb7f/qjDp4fWd8dAOG8ckiczUb4BlbuBHx2XHt9gFFpy8HQ/cW8lUsf+XJeBELLjIf/yFpO1FcVpwIO7JngMqxXon0C1hbXMOLFS6Ml7DUtyANqs+J7QtrhSb/5opJNa/gkg/GBXIuptWi4kqMjz1lVcg0IcTY=
  file_glob: true
  file: plantuml.eclipse.updatesite/target/plantuml.eclipse.updatesite-*-SNAPSHOT.zip
  on:
    repo: Hellmy/plantuml-eclipse-xtext
    tags: true
after_success:
  script: ./deploy.sh
env:
  global:
    GH_REF: github.com/Hellmy/plantuml-eclipse-xtext_update.git
    secure: Pq/nVKm/JeRhGc123VcRsaMWAJXQAdNDYeWFHsQdhDDdRSrwQ2p6Lf9gfXxC956hPFtochNU2JPu1shSMTeXVdNrdM+m1WrmLhWa9K/kpngoqYqC8NDTpnqVOUcr2KFcwpyFqeP+0UmQha8IDxOyftsqHIElxIf8mQcH4RSrkqVMxukPTpeQom6t2PCHTn8OYQtBRRZ93XovMqlMm1FIRTwECWqHvZ/oyArQvzT/y11YCRM0XhP4lwojAjfIs0sELyz4hjFFtdYkhaMfGK2znUCC5/B78hDrvzcJKUSZ8jJ3/XKuSaLnTa9I7WIDvMiN0/8r4keAO0eqTfFNXx/hECRWCNuSx1Jmt3rqwFNgIcT6hqBFnnaemyoPhayeJfkc7O8M1CVXBEIIbpce8fmODvt9iY18k8sr7Vrcze7qkdF1uRHonC6rvbAZthuTCT1moF0D7+D/IISG1bE0NT90arbVTLkVNusDrtB09Q2OFkdcGwJjfHRJydaqehoVsZ0/3u2xbjntg9m/ajDroRqoN8uTJphKNmZP++GDdxacULUjTn5aCp9q5oDB8n+xAWJa8lD3J2zwvMDVma43JExodUyZi420iLACh5BZ0z7yaobKK4R7ie1eAhU6Hf8H9ud7w8pg7UCCgG05P8ga+WK1f7xHtDW9tylC+FolnKHCvuE=
