/*
 * generated by Xtext
 */
package plantuml.eclipse.ui.contentassist

import plantuml.eclipse.ui.contentassist.AbstractPumlProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class PumlProposalProvider extends AbstractPumlProposalProvider {
}
