/*
 * generated by Xtext
 */
package plantuml.eclipse;

import org.eclipse.xtext.conversion.impl.AbstractDeclarativeValueConverterService;
import plantuml.eclipse.converter.PumlValueConverter;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PumlRuntimeModule extends plantuml.eclipse.AbstractPumlRuntimeModule {

	public Class<? extends AbstractDeclarativeValueConverterService> bindAbstractDeclarativeValueConverterService(){
		return PumlValueConverter.class;
	}
	
}
